name: Build & Push OrderService
on:
  push:
    branches: [ "main" ]
    paths:
      - 'OrderService/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -f OrderService/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/orderservice:${{ github.sha }} .

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/orderservice:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/orderservice:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/orderservice:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/orderservice:latest

     - name: Clone infra repo
        uses: actions/checkout@v3
        with:
          repository: moisescastro13/sabana-MicroServices-infra
          token: ${{ secrets.INFRA_REPO_TOKEN }}
          path: infra-repo

      - name: Update values.yaml with new image tag
        run: |
          sed -i "s|tag: .*|tag: '${{ github.sha }}'|" infra-repo/charts/orderservice/values.yaml

      - name: Commit and push changes to infra repo
        run: |
          cd infra-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Update OrderService image tag to ${{ github.sha }}"
          git push origin main